version: "3.7"

services:
    pigmyplusapp:
        image: mcr.microsoft.com/dotnet/framework/aspnet:4.8
        networks: 
            - hostsubnet
        ports:
            - "8000:80"
        volumes:
            - ./Publish/:C:\inetpub\wwwroot\
    sqldb:
        image: microsoft/mssql-server-windows-express
        networks: 
            hostsubnet:
                ipv4_address: 172.10.18.254
        ports:
            - "1433:1433"
        environment: 
            - sa_password=Sagar1
            - ACCEPT_EULA=Y
            - attach_dbs=[{'dbName':'PigmyPlus','dbFiles':['C:\\SQLServer\\PigmyPlus.mdf','C:\\SQLServer\\PigmyPlus_log.ldf']}]
        volumes: 
            - ./SQLServer/Db/:C:/SQLServer/

networks:
    hostsubnet:
        external: true
